#### general settings
name: KPNet_42
model: condition
use_tb_logger: true
distortion: sr
scale: 1
gpu_ids: [1]

#### datasets
datasets:
  train:
    name: Single_LDR2HDR
    mode: hdrtv
    dataroot_LQ: /home/wanghu/hdr/hdrtv/train_sdr_42_png_sub
    dataroot_GT: /home/wanghu/hdr/hdrtv/train_hdr_sub
    use_shuffle: true
    n_workers: 8
    batch_size: 12
    GT_size: 160
    use_flip: true
    use_rot: true
    condition: image
  val:
    name: Single_LDR2HDR
    mode: hdrtv
    dataroot_LQ: /home/Disk2/hdrtv/compress/qp42/valid/valid_sdr_sub
    dataroot_GT: /home/Disk2/hdrtv/compress/valid_true/hdr_sub
    condition: image

#### network structures
network_G:
  which_model_G: scale_3_brain_new1
  in_nc: 3
  out_nc: 3
  nf: 64 
  act_type: relu 

#### path
path:
  root: ./
#  pretrain_model_G: 
  strict_load: false
 # resume_state: 
#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-4
  lr_scheme: MultiStepLR # MultiStepLR | CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter:  550000 
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps: [200000, 300000, 400000, 500000]
  lr_gamma: 0.5

  pixel_criterion: l1 # l1 | l2 | tanh_l1 | tanh_l2
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 5e3

